Pick omsagent v1.3.4-15, install packages in pre-start, add uaa security logs

diff --git a/jobs/omsagent/templates/omsagent-ctl.erb b/jobs/omsagent/templates/omsagent-ctl.erb
--- a/jobs/omsagent/templates/omsagent-ctl.erb
+++ b/jobs/omsagent/templates/omsagent-ctl.erb
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-source /var/vcap/packages/omi/utils.sh
+source /var/vcap/packages/omsagent/utils.sh
 
 RUN_DIR=/var/vcap/sys/run/omsagent
 LOG_DIR=/var/vcap/sys/log/omsagent
@@ -8,77 +8,45 @@ LOG_DIR=/var/vcap/sys/log/omsagent
 PID_FILE=$RUN_DIR/omsagent.pid
 LOG_FILE=$LOG_DIR/omsagent.log
 
-OMS_BIN=/var/vcap/packages/omsagent/opt/bin/omsagent
-RUBY_BIN=/var/vcap/packages/omsagent/opt/ruby/bin/ruby
+RUBY_BIN=/opt/microsoft/omsagent/ruby/bin/ruby
 
+WORKSPACE_ID=<%= p('oms.workspace_id') %>
+OMS_BIN=/opt/microsoft/omsagent/bin/omsagent-${WORKSPACE_ID}
+OMS_VAR=/var/opt/microsoft/omsagent/${WORKSPACE_ID}
+CONF_DIR=/etc/opt/microsoft/omsagent/${WORKSPACE_ID}/conf/omsagent.d
+OMSAGENT_CONF=/etc/opt/microsoft/omsagent/${WORKSPACE_ID}/conf/omsagent.conf
 
 case $1 in
 
   start)
+
+    mkdir -p $RUN_DIR
 
     pid_guard $PID_FILE omsagent
 
     # Swap the order of hostname, as syslog uses the first name behind 127.0.0.1 as hostname
     sed -i 's/127\.0\.0\.1 localhost \(.*\)/127\.0\.0\.1 \1 localhost/g' /etc/hosts
 
-    # Write the onboard config
-    workspace_id=<%= p('oms.workspace_id') %>
-    workspace_key=<%= p('oms.workspace_key') %>
-
-    cat <<EOF > /etc/omsagent-onboard.conf 
-WORKSPACE_ID=$workspace_id
-SHARED_KEY=$workspace_key
-URL_TLD=opinsights.azure.com
-EOF
-
-    # Install packages
-    which dpkg > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        dpkg -i -E /var/vcap/packages/scx/scx-bosh-cimprov-*.deb
-        dpkg -i -E /var/vcap/packages/omsagent/omsagent-bosh-*.deb
-        dpkg -i -E /var/vcap/packages/omsconfig/omsconfig-bosh-*.deb
-    else
-        rpm -i /var/vcap/packages/scx/scx-bosh-cimprov-*.rpm
-        rpm -i /var/vcap/packages/omsagent/omsagent-bosh-*.rpm
-        rpm -i /var/vcap/packages/omsconfig/omsconfig-bosh-*.rpm
-    fi
-
-    # Add omsagent user to vcap group for diretory access for dsc
-    usermod -aG vcap omsagent
-
-    # Create symlinks for dsc 
-    mkdir -p /opt/microsoft
-    ln -s /var/vcap/packages/omsagent/opt /opt/microsoft/omsagent
-    ln -s /var/vcap/packages/omsconfig/opt /opt/microsoft/omsconfig
-    mkdir -p /etc/opt/microsoft
-    ln -s /var/vcap/packages/omsagent/etc /etc/opt/microsoft/omsagent
-    mkdir -p /var/opt/microsoft
-    ln -s /var/vcap/packages/omsagent/var /var/opt/microsoft/omsagent
-    mkdir -p /etc/opt/omi/conf
-    ln -s /var/vcap/packages/omi/etc/conf/omsconfig /etc/opt/omi/conf/omsconfig
-    chown -h omsagent:omsagent /var/opt/microsoft/omsagent
-    chown -h omsagent /etc/opt/omi/conf/omsconfig
-
     # Configure rsyslog if specfied
     rsyslog_selectors="<%= p('rsyslog.selector_list', []).join(' ') %>"
     rsyslog_port=<%= p('rsyslog.port', 25224) %>
     rsyslog_protocol=<%= p('rsyslog.protocol_type', 'udp') %>
     rsyslog_conf_file=/etc/rsyslog.d/95-omsagent.conf
-    omsagent_conf_file=/var/vcap/packages/omsagent/etc/conf/omsagent.conf
+    omsagent_syslog_conf_file=$CONF_DIR/syslog.conf
 
     # Set the initial configuration
-    cp /var/vcap/packages/omsagent/etc/sysconf/omsagent.conf $omsagent_conf_file
-    cp /var/vcap/packages/omsagent/etc/sysconf/rsyslog.conf $rsyslog_conf_file
+    cp /etc/opt/microsoft/omsagent/sysconf/syslog.conf.bk $omsagent_conf_file
+    cp /etc/opt/microsoft/omsagent/sysconf/95-omsagent.conf.bk $rsyslog_conf_file
 
     # Set rsyslog protocol
     conf_str="@"
     if [ "${rsyslog_protocol,,}" = tcp ]; then
         conf_str="@@"
     fi
-    sed -i "s/protocol_type \(udp\|tcp\)/protocol_type "${rsyslog_protocol,,}"/g" $omsagent_conf_file
+    sed -i "s/protocol_type \(udp\|tcp\)/protocol_type "${rsyslog_protocol,,}"/g" $omsagent_syslog_conf_file
 
     # Set rsyslog port
-    sed -i "s/port [0-9]*/port ${rsyslog_port}/g" $omsagent_conf_file
+    sed -i "s/port [0-9]*/port ${rsyslog_port}/g" $omsagent_syslog_conf_file
 
     # Set rsyslog selectors
     conf_str="${conf_str}127.0.0.1:${rsyslog_port,,}"
@@ -95,40 +63,44 @@ EOF
     service rsyslog restart
 
     # link the service_control file
-    rm /var/vcap/packages/omsagent/opt/bin/service_control
-    ln -s /var/vcap/jobs/omsagent/bin/omsagent-ctl /var/vcap/packages/omsagent/opt/bin/service_control
+    rm /opt/microsoft/omsagent/bin/service_control
+    ln -s /var/vcap/jobs/omsagent/bin/omsagent-ctl /opt/microsoft/omsagent/bin/service_control
 
-    $RUBY_BIN $OMS_BIN -d $PID_FILE -o $LOG_FILE --no-supervisor --user omsagent --group omiusers
+    $RUBY_BIN $OMS_BIN -d $PID_FILE -o $LOG_FILE --no-supervisor -c $OMSAGENT_CONF --user omsagent --group omiusers
 
+    # When two omsagent processes are started, the later one will update PID file but fails to run
+    # So here updates the PID file to the real running process
+    sleep 1
+    pidof $RUBY_BIN > $PID_FILE
     ;;
 
   stop)
 
     kill -sigkill `cat $PID_FILE`
     wait_until_process_stops $PID_FILE 5
-
     ;;
 
-  restart)
+  restart|reload)
 
     $0 stop
     pid_guard $PID_FILE omsagent
-    $RUBY_BIN $OMS_BIN -d $PID_FILE -o $LOG_FILE --no-supervisor --user omsagent --group omiusers
+    $RUBY_BIN $OMS_BIN -d $PID_FILE -o $LOG_FILE --no-supervisor -c $OMSAGENT_CONF --user omsagent --group omiusers
+    ;;
 
+  is-running)
+
+    is_process_running $PID_FILE
+    exit $?
     ;;
 
   find-systemd-dir)
 
     find_systemd_dir
-
     ;;
 
   *)
 
-    echo "Usage: $0 {start|stop|restart|find-systemd-dir}"
-
+    echo "Usage: $0 {start|stop|restart|reload|is-running|find-systemd-dir}"
     ;;
 
 esac
-
-
